import { MenuItem } from './types';

export const LUNCH_MENU: MenuItem[] = [
  {
    id: 'lunch-1',
    name: 'Spanish Smoky Paprika Chicken Bowl',
    category: 'Rice Bowls',
    menuType: 'Lunch',
    diet: 'nonveg',
    protein: '48g',
    calories: '620',
    carbs: '54g',
    fats: '14g',
    description: 'Slow-roasted herb chicken breast infused with authentic smoked paprika, steamed brown rice, charred bell peppers, and spiced black beans.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    isPopular: true,
  },
  {
    id: 'lunch-2',
    name: 'Dhaba Smoky Chicken Bowl',
    category: 'Rice Bowls',
    menuType: 'Lunch',
    diet: 'nonveg',
    protein: '46g',
    calories: '640',
    carbs: '58g',
    fats: '16g',
    description: 'Char-grilled tandoori chicken chunks tossed in homestyle rustic dhaba spices, aromatic jeera basmati rice, and fresh pickled kachumber.',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
    isPopular: true,
  },
  {
    id: 'lunch-3',
    name: 'Mexican Fiesta Chicken Bowl',
    category: 'Rice Bowls',
    menuType: 'Lunch',
    diet: 'nonveg',
    protein: '47g',
    calories: '590',
    carbs: '52g',
    fats: '13g',
    description: 'Zesty lime-cilantro chicken strips, sweet corn, roasted bell peppers, black beans, salsa roja, and fiber-dense wild brown rice.',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lunch-4',
    name: 'Hariyali Chicken Rice Bowl',
    category: 'Rice Bowls',
    menuType: 'Lunch',
    diet: 'nonveg',
    protein: '45g',
    calories: '610',
    carbs: '55g',
    fats: '15g',
    description: 'Succulent chicken breast marinated in fresh garden mint, coriander, and green chillies, served with tempered ghee rice and sautéed broccoli.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lunch-5',
    name: 'Chettinad Pepper Chicken Bowl',
    category: 'Rice Bowls',
    menuType: 'Lunch',
    diet: 'nonveg',
    protein: '48g',
    calories: '630',
    carbs: '56g',
    fats: '15g',
    description: 'Authentic stone-ground black pepper roasted chicken with toasted curry leaves, fennel seeds, and high-fiber red matta rice.',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lunch-6',
    name: 'Mediterranean Tikka Bowl',
    category: 'Rice Bowls',
    menuType: 'Lunch',
    diet: 'nonveg',
    protein: '49g',
    calories: '580',
    carbs: '48g',
    fats: '12g',
    description: 'Oven-baked lemon herb chicken skewers served over herbed pearl couscous, cucumber-olive medley, and velvety tahini garlic drizzle.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    isPopular: true,
  },
  {
    id: 'lunch-7',
    name: 'Lasooni Chicken Rice Bowl',
    category: 'Rice Bowls',
    menuType: 'Lunch',
    diet: 'nonveg',
    protein: '46g',
    calories: '620',
    carbs: '57g',
    fats: '14g',
    description: 'Golden roasted garlic glazed chicken fillet cooked in cold-pressed mustard oil with seasoned long-grain rice and steamed zucchini.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lunch-8',
    name: 'Arabian Chicken Kabsa Bowl',
    category: 'Rice Bowls',
    menuType: 'Lunch',
    diet: 'nonveg',
    protein: '47g',
    calories: '660',
    carbs: '60g',
    fats: '16g',
    description: 'Fragrant Arabian spiced chicken with black lime, cinnamon notes, toasted slivered almonds, and golden cardamom basmati rice.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lunch-9',
    name: 'Schezwan Fire Chicken Bowl',
    category: 'Rice Bowls',
    menuType: 'Lunch',
    diet: 'nonveg',
    protein: '45g',
    calories: '600',
    carbs: '53g',
    fats: '14g',
    description: 'Wok-tossed chicken chunks in in-house fermented dry-chilli Schezwan sauce, crunchy snow peas, and organic brown rice.',
    image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lunch-10',
    name: 'Chilli-Lime Chicken Bowl',
    category: 'Rice Bowls',
    menuType: 'Lunch',
    diet: 'nonveg',
    protein: '46g',
    calories: '570',
    carbs: '49g',
    fats: '11g',
    description: 'Crisp seared lean chicken tossed in cold-pressed lime reduction, crushed bird’s eye chilli, steamed tri-color quinoa, and avocado.',
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80',
  },
];

export const DINNER_MENU: MenuItem[] = [
  {
    id: 'dinner-1',
    name: 'Black Pepper Chicken Masala Plate',
    category: 'Indian Plates',
    menuType: 'Dinner',
    diet: 'nonveg',
    protein: '50g',
    calories: '670',
    carbs: '52g',
    fats: '15g',
    description: 'Fresh cracked peppercorn chicken slow-cooked with curry leaves and shallots. Served with 2 whole-wheat rotis and sprouted bean salad.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=800&q=80',
    isPopular: true,
  },
  {
    id: 'dinner-2',
    name: 'Afghani Chicken Shawarma',
    category: 'Wraps & Shawarma',
    menuType: 'Dinner',
    diet: 'nonveg',
    protein: '45g',
    calories: '550',
    carbs: '42g',
    fats: '16g',
    description: 'Cashew-yogurt marinated tender chicken rolled in 100% whole-wheat pita with crunchy iceberg lettuce, pickled onions, and low-fat garlic toum.',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
    isPopular: true,
  },
  {
    id: 'dinner-3',
    name: 'Kadai Egg Masala Plate',
    category: 'Indian Plates',
    menuType: 'Dinner',
    diet: 'nonveg',
    protein: '38g',
    calories: '520',
    carbs: '46g',
    fats: '16g',
    description: 'Farm-fresh boiled eggs sautéed in wok-crushed coriander and Kashmiri chilli gravy, accompanied by warm multigrain rotis and green salad.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'dinner-4',
    name: 'Tandoori Chicken Macaroni',
    category: 'Pasta',
    menuType: 'Dinner',
    diet: 'nonveg',
    protein: '46g',
    calories: '610',
    carbs: '56g',
    fats: '14g',
    description: 'Whole-wheat durum macaroni tossed in roasted tomato makhani cream sauce, topped with shredded smoky tandoori chicken breast.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d62817ee?auto=format&fit=crop&w=800&q=80',
    isPopular: true,
  },
  {
    id: 'dinner-5',
    name: 'Spicy Chicken Shawarma',
    category: 'Wraps & Shawarma',
    menuType: 'Dinner',
    diet: 'nonveg',
    protein: '44g',
    calories: '540',
    carbs: '44g',
    fats: '15g',
    description: 'Fiery harissa and paprika shredded chicken stuffed inside toasted whole-wheat flatbread with crisp cucumbers, tomatoes, and hung curd tzatziki.',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'dinner-6',
    name: 'Caesar Chicken Protein Salad',
    category: 'Salads',
    menuType: 'Dinner',
    diet: 'nonveg',
    protein: '48g',
    calories: '420',
    carbs: '18g',
    fats: '14g',
    description: 'Crisp baby romaine, Tuscan kale, seasoned garlic croutons, aged shaved parmesan, and flame-grilled chicken breast with light Greek yogurt dressing.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    isPopular: true,
  },
  {
    id: 'dinner-7',
    name: 'Lemon Pepper Chicken Salad',
    category: 'Salads',
    menuType: 'Dinner',
    diet: 'nonveg',
    protein: '47g',
    calories: '390',
    carbs: '16g',
    fats: '12g',
    description: 'Zesty lemon zest and cracked Tellicherry black pepper chicken tossed with mixed baby greens, toasted pumpkin seeds, and cold-pressed olive oil.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'dinner-8',
    name: 'Teriyaki Chicken Crunch Salad',
    category: 'Salads',
    menuType: 'Dinner',
    diet: 'nonveg',
    protein: '45g',
    calories: '440',
    carbs: '24g',
    fats: '14g',
    description: 'Low-sodium soy glazed teriyaki chicken atop purple cabbage, grated carrots, edamame, and toasted slivered almonds with sesame ginger vinaigrette.',
    image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'dinner-9',
    name: 'Mediterranean Chicken Power Salad',
    category: 'Salads',
    menuType: 'Dinner',
    diet: 'nonveg',
    protein: '49g',
    calories: '430',
    carbs: '22g',
    fats: '15g',
    description: 'Oregano char-grilled chicken slices with kalamata olives, diced English cucumbers, cherry tomatoes, and crumbled low-fat feta cheese.',
    image: 'https://images.unsplash.com/photo-1547496502-ffa22d388377?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'dinner-10',
    name: 'Smoky Paprika Chicken Salad',
    category: 'Salads',
    menuType: 'Dinner',
    diet: 'nonveg',
    protein: '46g',
    calories: '400',
    carbs: '19g',
    fats: '13g',
    description: 'Spanish smoked paprika dry-rubbed chicken with crisp organic spinach, roasted bell pepper strips, toasted walnuts, and citrus balsamic reduction.',
    image: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=800&q=80',
  },
];

export const CATEGORIES = [
  'All',
  'Rice Bowls',
  'Wraps & Shawarma',
  'Pasta',
  'Salads',
  'Indian Plates',
] as const;

export const HIGHLIGHT_CATEGORIES = [
  {
    name: 'Rice Bowls',
    tagline: 'Wholesome & Balanced',
    description: 'Nutrient-rich grains paired with seasoned lean proteins and fiber-packed veggies.',
    protein: '45g - 49g',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Wraps & Shawarma',
    tagline: 'Fresh & Filling',
    description: '100% whole-wheat flatbreads stuffed with juicy marinades and house-made light toum.',
    protein: '43g - 45g',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Pasta',
    tagline: 'Comfort Food, Healthy Macros',
    description: 'Whole-durum wheat pastas tossed in protein-rich herb makhani sauces.',
    protein: '46g+',
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d62817ee?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Salads',
    tagline: 'Light, Crisp & Nutritious',
    description: 'Crisp organic greens, cold-pressed dressings, healthy seeds, and flame-grilled cuts.',
    protein: '45g - 49g',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Indian Plates',
    tagline: 'Homestyle High-Protein',
    description: 'Comforting, familiar recipes cooked in zero preservatives with whole-wheat rotis.',
    protein: '48g - 50g',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
  },
];
